# Generated by Django 4.1 on 2022-10-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listing_alter_user_id_watchlist_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
