# Generated by Django 4.1 on 2022-10-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='bid',
        ),
    ]
