# Generated by Django 4.1 on 2022-11-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_options_rename_current_bid_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(default='', max_length=64),
        ),
    ]
