# Generated by Django 4.1 on 2022-11-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid', 'item']},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['watcher', 'item']},
        ),
    ]
