# Generated by Django 4.1 on 2022-11-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_options_alter_watchlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['item', '-created_on']},
        ),
    ]
